Use primary active color for btn-group selection
SUSE/openstack-dashboard-theme-SUSE pull request #14
Opened 2019-03-28 19:43 UTC by dotNomad

Active buttons in button groups comprised of default buttons are
difficult to identify. The selection is only signified by a slight
shadow. Change to use the primary, active, green color for easy
identification.

2019-03-28 19:45 UTC, dotNomad commented
The easiest location to see the change is under Compute > Instances. Click "Launch Instance" and go to the Source tab in the modal. 
"Create New Volume" and "Delete Volume on Instance Delete" both use button groups with default buttons.

2019-03-28 22:33 UTC, jeremy-moffitt approved these changes
LGTM, much clearer than the shadow-alone from before

2019-03-29 19:09 UTC, ghost requested changes
@dotNomad  code looks good, but you might need a Jira item for the commit.

2019-03-29 21:35 UTC, dotNomad commented
@guglo I've created a Jira ticket for this and changed the PR title to reflect it. Thanks

2019-03-29 22:17 UTC, ghost approved these changes
@dotNomad  thanks for the fix!

2019-03-29 22:18 UTC, merged