SCRD-6919 Use SUSE colors throughout
SUSE/openstack-dashboard-theme-SUSE pull request #8
Opened 2019-02-01 18:32 UTC by GarySmith

Update the appropriate variables to use SUSE colors everywhere.  Per the
guidance in the EOS design system pertaining to minimum contrast ratios,
a number of controls now use black text on colored background, which
is noticeably different from the standard bootstrap styling. Several
bootstrap components use colors derived programatically from the base
color (SUSE green in our case), and thus differ from the official color
variants; these include pie charts and certain disabled components.

Change-Id: I92cadda94b1f451a1d8a414efdcc9fb14b892133

2019-02-05 19:42 UTC, dotNomad requested changes
- Looks like we have adjusted the button colors, but the hover colors are not SUSE colors nor is some of the text colors. Will have to wait on guidelines for the buttons though before making changes
- `a.list-group-item, button.list-group-item` is using `color: #555`
- Panels don't appear to be using a SUSE color border, pretty minor

2019-02-05 21:59 UTC, jeremy-moffitt submitted a review, later dismissed
Looks good to me, we should review with UX once it lands

2019-02-05 22:01 UTC, jeremy-moffitt commented
> * Looks like we have adjusted the button colors, but the hover colors are not SUSE colors nor is some of the text colors. Will have to wait on guidelines for the buttons though before making changes
> * `a.list-group-item, button.list-group-item` is using `color: #555`
> * Panels don't appear to be using a SUSE color border, pretty minor

@dotNomad which of these do you want @GarySmith to address before merging?

2019-02-05 22:09 UTC, GarySmith commented
I just noticed that comment. Let me provide an updated commit.

2019-02-05 23:39 UTC, jeremy-moffitt approved these changes
the dark menu bar is really dark... and the hover color on the yellow buttons is very orange, but overall looks ok to me

2019-02-06 18:16 UTC, dotNomad commented
Thanks for the changes. Looks great.

2019-02-06 18:16 UTC, dotNomad approved these changes

2019-02-06 18:17 UTC, merged