SCRD-6919 Address layout problems with smaller screens
SUSE/openstack-dashboard-theme-SUSE pull request #9
Opened 2019-02-08 17:39 UTC by GarySmith

The styling attempted to visually merge the top title bar with the areas
below it (the left nav bar and the main content window), and to force
the left navbar to be drawn when it otherwise would not be. This caused
a number problems when viewing on a modest sized screen (1024 width) or
when resizing.

Removed some of the custom nav bar forced styling and let the
underlying styles of horizon and bootstrap correctly hide and show
the navbar when appropriate.  Also collapsed some of the repetitive
css into more friendly scss nested styles.

2019-02-08 17:51 UTC, jeremy-moffitt commented
on my local system with this update (and with your VM as the backend) I get a django error on the `network topology` page... I dont *think* its theme related, but if I load up the Horizon on the VM directly (which doesnt have the latest version of this) the same page works... so that might be worth double checking

2019-02-08 18:18 UTC, jeremy-moffitt commented
as long as we can confirm that the topology issue isnt tied to the theme, the rest of this looks good! heck of a cleanup from yesterday

2019-02-08 18:22 UTC, GarySmith commented
> on my local system with this update (and with your VM as the backend) I get a django error on the `network topology` page... I dont _think_ its theme related, but if I load up the Horizon on the VM directly (which doesnt have the latest version of this) the same page works... so that might be worth double checking

I installed this pull request onto http://10.86.2.181:8000 , so you can see it running there. It does not have these error messages.

2019-02-08 18:26 UTC, jeremy-moffitt submitted a review, later dismissed
LGTM, much better interaction at low resolutions

2019-02-08 19:04 UTC, guglo commented
@GarySmith  thanks for the fixes. I tried it looks good. The only issue I saw is sometimes the side bar is not all the way down. I am not sure it matters or not. I remember Cynthia helped me fixed that problem a while ago.

2019-02-08 19:08 UTC, jeremy-moffitt commented
huh, I thought I saw the sidebar go all the way down, I may need to reload

2019-02-08 19:13 UTC, GarySmith commented
> @GarySmith thanks for the fixes. I tried it looks good. The only issue I saw is sometimes the side bar is not all the way down. I am not sure it matters. I remember Cynthia helped me fixed that problem a while ago.

I haven't seen this anywhere. Can you give any details on how I might reproduce that?

2019-02-08 19:13 UTC, jeremy-moffitt commented
ah! I see the issue on pages that scroll vertically... maybe try 100vmax rather than 100vh

2019-02-08 19:14 UTC, GarySmith commented
> ah! I see the issue on pages that scroll vertically... maybe try 100vmax rather than 100vh



> ah! I see the issue on pages that scroll vertically... maybe try 100vmax rather than 100vh

Thanks, will do.

2019-02-08 19:24 UTC, guglo commented
@GarySmith  I sent you the picture in private chat

2019-02-08 19:39 UTC, GarySmith commented
> ah! I see the issue on pages that scroll vertically... maybe try 100vmax rather than 100vh for the sidebar height

Tried that, but it really doesn't work on square layouts or any screen where the height is greater than width. I'm open to any other ideas; nothing I am trying is working

2019-02-08 21:12 UTC, jeremy-moffitt commented
one potential fix for this... give the body an explicit background-color that matches the sidebar ... then give the content_body an explicit background color of "white"... change the "padding-left: 220px" to "margin-left 220px" on the #content_body css entry .... there may be a better way, thats just one hack at it

2019-02-08 21:29 UTC, GarySmith commented
> one potential fix for this... give the main_content element an explicit background-color (#071B2A) that matches the sidebar ... then give the content_body an explicit background color of "white"... change the "padding-left: 220px" to "margin-left 220px" on the #content_body css entry .... there may be a better way, thats just one hack at it
> 
> I havent confirmed how this solution impacts horizontally scrolling pages yet (though there should be less of those after the previous changes)

I was thinking along those same lines but couldn't get it to work, but your post made my retry and I found a solution that seems to work without monkeying with margins/padding

2019-02-08 21:32 UTC, GarySmith commented
> > one potential fix for this... give the main_content element an explicit background-color (#071B2A) that matches the sidebar ... then give the content_body an explicit background color of "white"... change the "padding-left: 220px" to "margin-left 220px" on the #content_body css entry .... there may be a better way, thats just one hack at it
> > I havent confirmed how this solution impacts horizontally scrolling pages yet (though there should be less of those after the previous changes)
> 
> I was thinking along those same lines but couldn't get it to work, but your post made my retry and I found a solution that seems to work without monkeying with margins/padding

Doh, that doesn't work either. On a window with limited vertical content, the bottom of the screen is painted with the dark blue background.

2019-02-08 21:48 UTC, GarySmith commented
> > > one potential fix for this... give the main_content element an explicit background-color (#071B2A) that matches the sidebar ... then give the content_body an explicit background color of "white"... change the "padding-left: 220px" to "margin-left 220px" on the #content_body css entry .... there may be a better way, thats just one hack at it
> > > I havent confirmed how this solution impacts horizontally scrolling pages yet (though there should be less of those after the previous changes)
> > 
> > 
> > I was thinking along those same lines but couldn't get it to work, but your post made my retry and I found a solution that seems to work without monkeying with margins/padding
> 
> Doh, that doesn't work either. On a window with limited vertical content, the bottom of the screen is painted with the dark blue background.

And now that I've seen it once, I cannot find such a short screen again in any of the menus.

2019-02-08 22:01 UTC, ghost submitted a review, later dismissed
@GarySmith  Thanks for the changes! LGTM

2019-02-08 22:35 UTC, dotNomad requested changes
- The two hamburger menu buttons that appear below 768px width do not have a SUSE border or hover color. May want to use `#071B2A` we seem to be using that for similar color replacements.
- Personally the white on blue, then abrupt blue/grey on white navbar below 768px is rather jarring. Would it be possible to make it a single color background?
- Should it be possible to open both hamburger menus at the same time? I would expect when opening one the other would automatically close.
- The hamburger menus gain focus when clicking them which gets especially confusing when swapping between them, or clicking other things on the screen. I'm thinking they should remain a single color when focused, or should only be colored when their menu is open
- The z-index for the sidebar is 3, which matches the z-index for the pagination meaning the pagination will be over the sidebar when its expanded. This can be seen on the theme-preview page.
- The new change changing the body background-color leads to an odd situation on Project > Compute > Instances where you get this:  ![table actions to the right](https://user-images.githubusercontent.com/19917631/52509660-db4b6a00-2bad-11e9-9d2d-8f45e77a377a.png)


The actual functionality of the two menus seems to be working great. It is fully covering the left side, and is correctly colored as far as I can tell.

2019-02-12 19:28 UTC, GarySmith commented
> * The two hamburger menu buttons that appear below 768px width do not have a SUSE border or hover color. May want to use `#071B2A` we seem to be using that for similar color replacements.

Done

> * Personally the white on blue, then abrupt blue/grey on white navbar below 768px is rather jarring. Would it be possible to make it a single color background?

I agree that the dark menu with the light body is jarring, but I'm not sure what alternative exists withing the SUSE color scheme. Feel free to submit a PR that addresses this.

> * Should it be possible to open both hamburger menus at the same time? I would expect when opening one the other would automatically close.

The current behavior matches that in vanilla horizon. Behavior changes would fall outside of styling and would require patching the horizon source, and maintaining those patches in IBS, and I don't think we want to go there.

> * The hamburger menus gain focus when clicking them which gets especially confusing when swapping between them, or clicking other things on the screen. I'm thinking they should remain a single color when focused, or should only be colored when their menu is open

Agreed, but this is also the standard behavior in horizon (see previous comment about modifying behavior)

> * The z-index for the sidebar is 3, which matches the z-index for the pagination meaning the pagination will be over the sidebar when its expanded. This can be seen on the theme-preview page.

I'm not sure I understand the problem. Below is a screenshot with scrolling and an expanded navbar, and to me, it looks fine that the scrollbar is on top of the sidebar. Perhaps I'm missing something?

![screenshot_2019-02-12_11-20-03](https://user-images.githubusercontent.com/1018493/52662474-279def00-2eb9-11e9-807d-6b6bae671d96.png)


> * The new change changing the body background-color leads to an odd situation on Project > Compute > Instances where you get this:  ![table actions to the right](https://user-images.githubusercontent.com/19917631/52509660-db4b6a00-2bad-11e9-9d2d-8f45e77a377a.png)

Done.

> The actual functionality of the two menus seems to be working great. It is fully covering the left side, and is correctly colored as far as I can tell.

2019-02-12 20:58 UTC, dotNomad requested changes
Definitely don't want to change vanilla Horizon behavior, thats outside the scope of the theme as you said.

Looks like all but one of my issues has been addressed:
> The z-index for the sidebar is 3, which matches the z-index for the pagination meaning the pagination will be over the sidebar when its expanded. This can be seen on the theme-preview page.

You can see this occuring here on the Theme Preview page
![zindex-pagination](https://user-images.githubusercontent.com/19917631/52667480-cfb9b500-2ec5-11e9-88f9-7a4de03f5b5e.png)

2019-02-12 21:30 UTC, GarySmith commented
I don't mean to be dense, but I'm not clear what the problem is. I would expect both the vertical and horizontal scroll bars to be in front of / above the content.

2019-02-12 23:18 UTC, dotNomad commented
In the image above the current page indicator on the pagination component is above the sidebar. The "1" inside the green square is above the vertical sidebar.

I think the confusion is I'm not talking about the scroll bars, but the sidebar (the vertical menu).

2019-02-12 23:34 UTC, GarySmith commented
ok, I get it now. I was interpreting pagination controls as scroll bars, which is not what you meant

2019-02-13 17:48 UTC, dotNomad approved these changes

2019-02-13 17:49 UTC, dotNomad commented
Looking good with the changes :+1:

2019-02-13 20:48 UTC, jeremy-moffitt approved these changes
LGTM, thanks for the additional fixes

2019-02-13 20:48 UTC, merged